# Generated by Django 3.2.7 on 2021-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_first_name',
            new_name='s_full_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='t_first_name',
            new_name='t_full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='s_last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='t_last_name',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_title',
            field=models.CharField(max_length=30),
        ),
    ]
