# Generated by Django 3.2.7 on 2021-10-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211009_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='student_username',
        ),
    ]
