# Generated by Django 3.2.7 on 2021-10-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_student_name_student_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_date',
            field=models.FloatField(),
        ),
    ]
