# Generated by Django 3.2.8 on 2021-10-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_assignment_assignment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='submitted_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.teacher'),
        ),
    ]
