# Generated by Django 3.2.8 on 2021-10-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_submissions_submitted_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submitted_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.assignmenttitle'),
        ),
    ]
