# Generated by Django 3.2.8 on 2021-10-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20211016_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.assignmenttitle'),
        ),
    ]
