# Generated by Django 3.2.8 on 2021-10-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_assignment_assignment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_title',
            field=models.CharField(max_length=30),
        ),
    ]
