# Generated by Django 3.2.8 on 2021-10-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_assignment_assignment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='submitted_title',
        ),
        migrations.DeleteModel(
            name='AssignmentTitle',
        ),
    ]
