# Generated by Django 3.2.8 on 2021-10-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20211016_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_status',
            field=models.BooleanField(default=False),
        ),
    ]
