# Generated by Django 3.2.8 on 2021-10-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_assignment_assignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_status',
        ),
        migrations.AddField(
            model_name='submissions',
            name='assignment_status',
            field=models.BooleanField(default=False),
        ),
    ]
