# Generated by Django 3.2.8 on 2021-10-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20211020_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='assignment_status',
            new_name='sub_status',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_status',
            field=models.BooleanField(default=False),
        ),
    ]
