# Generated by Django 3.2.8 on 2021-10-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_submissions_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='project.teacher'),
        ),
    ]
