# Generated by Django 3.2.8 on 2021-10-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_teacher_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='marks_obtained',
            field=models.FloatField(null=True),
        ),
    ]
