# Generated by Django 3.2.8 on 2021-11-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20211021_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='submission_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
