# Generated by Django 3.2.8 on 2021-11-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_assignment_assignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_status',
        ),
    ]
